// <auto-generated />
using System;
using APIweb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIweb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240524175659_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIweb.Models.Produto", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("dataChegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dataEmbarque")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("exportador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("freteModo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("importador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nomeProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("paisDeDestino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("paisDeOrigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("valorUnitario")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
